build:
  maxIssues: 0

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
      - Preview

style:
  MaxLineLength:
    active: true
    maxLineLength: 140
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - Preview
